<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataLogging.Core\DataLogging.Core.csproj" />
    <ProjectReference Include="..\DataLogging.Ingestion\DataLogging.Ingestion.csproj" />
    <ProjectReference Include="..\DataLogging.MockHardware\DataLogging.MockHardware.csproj" />
    <ProjectReference Include="..\DataLogging.Storage\DataLogging.Storage.csproj" />
    <ProjectReference Include="..\DataLogging.Sync\DataLogging.Sync.csproj" />
    <ProjectReference Include="..\DataLogging.Analysis\DataLogging.Analysis.csproj" />
  </ItemGroup>

</Project>
